### ISSUE TITLE
运行gen_crop.py失败

### ISSUE THREAD

**Issue by John-Wi1es** [dawn-ech/YOLC#15]
conda环境如下：
cudatoolkit==10.2.89
cudnn==7.6.5
torch==1.10.1
mmcv-full==1.7.1
mmdet==2.26.0
运行时出现如下报错：ImportError: DLL load failed while importing _ext: 找不到指定的程序。
请问下是环境配置有问题么？（本地安装的cuda==11.4，nvcc==11.4）

**Comment by John-Wi1es** [comment]
补充一下环境配置需求，yapf<0.31.0,高于此版本需要手动修改mmcv.utils下的config.py文件中text, _ = FormatCode(text, style_config=yapf_style, verify=True)参数

**Comment by dawn-ech** [comment]
已经解决了吗？这个问题没遇到过

**Comment by John-Wi1es** [comment]
已经解决了，可能是torch版本太低的问题，更新环境配置为以下配置后没有出现该问题了，
cudatoolkit==11.3.1
cudnn==8.6.2
torch==1.12.0
mmcv-full==1.7.1
mmdet==2.26.0
可能是因为torch版本较低引起的，另外问下我5G显存的quadro-p2200单卡训练需要1200多天是否正常？（公司电脑太差了，又不舍得花钱升级配置）如果作者您能上传训练好的权重将不胜感激。[训练参数sample_per_gpu=2，=4的时候显存会溢出；lr=0.00125*0.25]

**Comment by dawn-ech** [comment]
感觉是卡的性能不够比较慢，训练好的权重已经上传，请在README中查看

**Comment by John-Wi1es** [comment]
感谢分享，我已经租了一个4x4090D的云服务器进行训练，大概需要1.5天左右，感觉4090相较3090提升不是很大。
