### ISSUE TITLE
Nothing about Local Scale Module

### ISSUE THREAD

**Issue by 1430329743** [dawn-ech/YOLC#3]
Could you please advise why there is no effective information about the Local Scale Module in your open-source code?

**Comment by dawn-ech** [comment]
Hi, LSM (Local Scale Module) is in yolc_head.py. Please refer to https://github.com/dawn-ech/YOLC/blob/3c498c8bfab284db66caa82607115580f5b4f2ee/models/dense_heads/yolc_head.py#L616.
